language: java
jdk:
- openjdk11
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
deploy:
  provider: heroku
  app: http4k-bootstrap
  api_key:
    secure: jojwFmbZUzFzBHywJFrB8Jy/bfmrAjkkcqHuoKwseHHLnXBFz8OHiYT1PVwmCZr4F38yjNxFbF4DYhS9xLeCYFeFkwqO8VChJjw+XTCydSj5Vs+abpbZK9GNpKWfxS47z4pnkQtXok5MgjBeJTgMQa6bc1cuv9YDF8Qm0I0c3VMBFuXDwrEg5ITmhFCdKTeE3M4dS7Q48pd7+LuND6NSG82gWvEqLifTIPoe/YyczgyD1X0JcsEpEk/hAD5vnbL3wqxneW+WOvF++W1t+IJb39aZFtZsJM1rGa87PYgdeNTkCAtdLs8IBHC8RhVjTvPwcxu4yMwLZz8QzbXtrwQVElZBL3Zknb69IPgchZ2rQYbSUWFSeUicPOzhZWN8L5TUO0nZrnKq5pSYDWptvGF293u8PQITTNAGDdETGnd0phJoGaUFcGD2fzmHPs2r3x6XfbgmuSBzMUxWglqItWsQqc/UbuFR//neBKgW9tI38t+fEPlugIG2Z1VVCy1NOZYFAZOj/FVDRXogz+RzJHgqcZLnhX5sLWLXiuXcyEI6hIW9mvfyq9/5d+007GoLd2uE7VQPLKYYPyQp4ZpX+NO3SAqzg1GUVjZwcJ9CNqLE3qlL1gyeuh+1UMGdmHQ95CjzWMJU3+262+WthNqaOEny8HbYvanlSxV/pMCsnXLBYzE=
